// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_FAPhsYWeihnXGVZTnp6sLbr-DHSrRYQ',
    appId: '1:970930480772:web:0a1b4c7e99d8f4518b44d1',
    messagingSenderId: '970930480772',
    projectId: 'marketing-up-app',
    authDomain: 'marketing-up-app.firebaseapp.com',
    storageBucket: 'marketing-up-app.appspot.com',
    measurementId: 'G-2DSN8T16VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjAcgow-4CQ79fpx6VA18WyF5B36OwPE0',
    appId: '1:970930480772:android:89c9a46a906b221c8b44d1',
    messagingSenderId: '970930480772',
    projectId: 'marketing-up-app',
    storageBucket: 'marketing-up-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEVjKnxI3Z4t1ZPVYZ8IeoUzJYy1ieQ3Y',
    appId: '1:970930480772:ios:0d99cdb34fe953168b44d1',
    messagingSenderId: '970930480772',
    projectId: 'marketing-up-app',
    storageBucket: 'marketing-up-app.appspot.com',
    iosBundleId: 'com.hrsoftbd.marketingup.marketingUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEVjKnxI3Z4t1ZPVYZ8IeoUzJYy1ieQ3Y',
    appId: '1:970930480772:ios:0d99cdb34fe953168b44d1',
    messagingSenderId: '970930480772',
    projectId: 'marketing-up-app',
    storageBucket: 'marketing-up-app.appspot.com',
    iosBundleId: 'com.hrsoftbd.marketingup.marketingUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_FAPhsYWeihnXGVZTnp6sLbr-DHSrRYQ',
    appId: '1:970930480772:web:c6e3c483c071cabd8b44d1',
    messagingSenderId: '970930480772',
    projectId: 'marketing-up-app',
    authDomain: 'marketing-up-app.firebaseapp.com',
    storageBucket: 'marketing-up-app.appspot.com',
    measurementId: 'G-0XHTYY5SJY',
  );
}
